# SafeGuard Panel is a commercial product, not a donation-funded project.
# The "Sponsor" button simply points to our site, where managed hosting,
# priority support, and OEM/redistribution licensing are available.
# (Remove this file if you'd rather not show a Sponsor button at all.)
custom: ["https://safeguardpanel.ca"]
